### ISSUE TITLE
api: use ISO 8601 Z date format

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-records-rest#19]
Currently, the REST API reply contains:

```console 
$ curl http://0.0.0.0:5000/api/records/1
{
  "created": "Fri, 11 Dec 2015 12:42:46 GMT", 
  "id": "1", 
  "links": {
    "self": "http://0.0.0.0:5000/api/records/1"
  }, 
  "metadata": {
    "title": "Invenio 3 rocks"
  }, 
  "revision": 1, 
  "updated": "Fri, 11 Dec 2015 12:42:46 GMT"
}
```

The provided date format is human-oriented, while it would be better to use machine-oriented ISO 8601 Z format in the APIs.  Example: `2015-05-26T11:00:00Z`.

For inspiration, see how we addresed this in ClaimStore:
- issue: https://github.com/inveniosoftware/claimstore/issues/6
- implementation: https://github.com/inveniosoftware/claimstore/pull/29

**Comment by nharraud** [comment]
@tiborsimko `datetime.isoformat` returns the timezone as `+HH:MM` (i.e. `+00:00` for UTC) instead of `Z`. If that's ok with you, I would prefer to use the provided implementation rather than recommend the use of a custom format string which can contain typo (if we choose one way to do it, it should be the same in every module).

**Comment by jirikuncar** [comment]
In case ISO 8601 'Z' is a problem: https://pypi.python.org/pypi/iso8601

**Comment by nharraud** [comment]
@jirikuncar In this case the problem is not for parsing but for generating. Both `Z` and `+HH:MM` formats are valid ISO 8601 formats. Python's `datetime.isoformat` generates only the second one. Thus the only solution I see to generate a `Z` is to provide a format string, which might contain a typo if it is used in many places. That's why I would rather use `datetime.isoformat` even if it uses more bandwidth.
