### ISSUE TITLE
api: Content-Type for import

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-records-rest#9]
How do we specify with *DoJSON* rules should be used for `application/marc` for different variants MARC21 Bibliographic, MARC21 Authority?

**Comment by nharraud** [comment]
Is there something in MARC21 standard specific to Authority or Bibliographic records? Otherwise I don't think we can do it with schemas.

If this is not possible, what we could do is use multiple instances of invenio-records-rest bound to different endpoints `/records`, `/authors`... as @lnielsen proposed. We could then configure invenio-records-rest to register additional fields in the record, or just send a specific signal and leave that work to some third-party module.

**Comment by lnielsen** [comment]
I think this is highly related to #8 and #7 and more generic than specifying DoJSON rules.

1) How we specify our possible export resource representations (MARC (with dojson), DataCite, DublinCore, BibTeX, ...)
2) How do we specify our possible import resource representations (same list as above).

First the records rest must have dynamic blueprints (#7) so that we can resolve to both ``/records`` and ``/authors``, and ... Next, for each endpoint we need to map mime types to custom code that transforms the input to JSON (and

```
RECORDS_API_ENDPOINTS = {
'records': {
    'route': '/records',
    'pid_type': 'redid',
    'serialisations': {
        'application/xml+marc': ....nice way of specifying MARC serialiser....,
    },
    'deserialisation': {
        'application/xml+datacite': .....
    }
}
}
```

We could provide default so you wouldn't need to specify anything if you wanted just the standard.

**Comment by jirikuncar** [comment]
One can use content type parameters e.g. `application/xml+marc;type=holdings` to specify serializers.
